### PR TITLE
FastCV for OpenCV acceleration

### PR DESCRIPTION
**Pull request by sssanjee-quic**
FastCV for the OpenCV Acceleration on the Qualcomm's Snapdragon Chipsets.
Change-Id: Ic94c616f17b3cbd7a41fb5af1a44652e4f431c3b

### CODE REVIEW

**Comment by asmorkalov** [comment]
@sssanjee-quic The license is fully proprietary. It does not allow FastCV usage without Qualcomm permit.

**Comment by sssanjee-quic** [comment]
Hi @asmorkalov , Updated the License files, can you please check once

**Review by quic-tsoni — COMMENTED** [review]
What is the use of Change-ID here?

**Comment by quic-tsoni** [comment]
Please check the change-ID comment.

**Comment by quic-xuezha** [comment]
> Please check the change-ID comment.

removed

**Comment by asmorkalov** [comment]
Pushed manually to fastcv/4.x_20241024 branch.

https://github.com/opencv/opencv_3rdparty/tree/fastcv/4.x_20241024

**Pull request closed without merging**
