### PR TITLE
Ffmpeg/master 20160215

### PR DESCRIPTION
**Pull request by peters**
Add support for VP8 / V9 and target ffmpeg 3.0

Related to https://github.com/Itseez/opencv/issues/6308

### CODE REVIEW

**Comment by alalek** [comment]
@peters Thanks!
Branches with "date" should be one-commit leaves with blob binary data and they should not be touched (no extra commits for them). You need to update configuration branch - for ffmpeg it is ffmpeg/master
Could you please rebase this commits on "ffmpeg/master" branch (without binaries) and squash commits by this scheme: 1st+3rd (related to ffmpeg 3.0) and 2nd+4th (related to libvpx).

You can use this command (`upstream` is from [here](https://help.github.com/articles/configuring-a-remote-for-a-fork/)):

```
git rebase -i upstream/ffmpeg/master
```

**Comment by peters** [comment]
Great! I'll try to get this done by the end of the week :)

**Comment by peters** [comment]
Btw, I would like to add some additional options to the build script that will allow you to enable hardware acceleration using DXVA2 and intel media sdk (new skylake architecture has hybrid support for encoding VP9). I believe GEN8 has full hardware acceleration for VP8. These options will of course be turned off by default.

**Comment by alalek** [comment]
BTW, I had some experiments [here](https://github.com/alalek/opencv_3rdparty/commits/ffmpeg/master) ([binaries](https://github.com/alalek/opencv_3rdparty/tree/ffmpeg/master_20160325)).

**Comment by peters** [comment]
I've rebased my changes.

**Pull request closed without merging**
